// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var cssClassName = "Comment Comment-hidden";

var downvotes = 10;

var upvotes = 5;

exports.downvotes = downvotes;
exports.upvotes = upvotes;
exports.cssClassName = cssClassName;
/* No side effect */
