// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var bookName = "Deep Work";

var tagline = "Rules for Focused Success in a Distracted World";

var book2 = "Real World OCaml: Functional programming for the masses";

var book = "Deep Work: Rules for Focused Success in a Distracted World";

exports.bookName = bookName;
exports.tagline = tagline;
exports.book2 = book2;
exports.book = book;
/* No side effect */
