// Generated by ReScript, PLEASE EDIT WITH CARE


var bookName = "Deep Work";

var tagline = "Rules for Focused Success in a Distracted World";

var book2 = "Real World OCaml: Functional programming for the masses";

var book = bookName + ": " + tagline;

export {
  bookName ,
  tagline ,
  book2 ,
  book ,
}
/* No side effect */
