// Generated by ReScript, PLEASE EDIT WITH CARE


var sum = 3;

var sum2 = sum + 3 | 0;

var two = 2;

var one = 1;

var three = 3;

export {
  two ,
  one ,
  three ,
  sum ,
  sum2 ,
}
/* No side effect */
