// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var sum = 3;

var sum2 = sum + 3 | 0;

var two = 2;

var one = 1;

var three = 3;

exports.two = two;
exports.one = one;
exports.three = three;
exports.sum = sum;
exports.sum2 = sum2;
/* No side effect */
