// Generated by ReScript, PLEASE EDIT WITH CARE


var hello7 = [
  1,
  2,
  3
];

var hello10 = "abcefg";

var hello11 = 1 + 1.1;

var runningTotal = 2;

var runningTotal$1 = Math.imul(runningTotal, 3);

var sumOfFloats = 1 + 2.2 + 3.14;

var joinedStrings = "Hello, World!";

var hello = "안녕";

var hello2 = 1;

var hello3 = 1;

var hello4 = true;

var hello5 = false;

var hello6 = /* '1' */49;

var hello8 = [
  1,
  2,
  3
];

var sumOfInts = 10;

export {
  hello ,
  hello2 ,
  hello3 ,
  hello4 ,
  hello5 ,
  hello6 ,
  hello7 ,
  hello8 ,
  hello10 ,
  hello11 ,
  runningTotal$1 as runningTotal,
  sumOfInts ,
  sumOfFloats ,
  joinedStrings ,
}
/* No side effect */
