// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SimpleTest from "./simpleTest.js";

var cssClassName = "Comment Comment-hidden";

SimpleTest.assertEqual(26, 0, "[exercise 1] Calculate discount for total amount of shopping cart");

function somefn(firstname, lastname) {
  return firstname + " " + lastname;
}

var downvotes = 10;

var upvotes = 5;

var total = 500;

var cartTotal = 220;

var discount = 0;

export {
  downvotes ,
  upvotes ,
  cssClassName ,
  total ,
  cartTotal ,
  discount ,
  somefn ,
}
/*  Not a pure module */
