// Generated by ReScript, PLEASE EDIT WITH CARE


var cssClassName = "Comment Comment-hidden";

var downvotes = 10;

var upvotes = 5;

export {
  downvotes ,
  upvotes ,
  cssClassName ,
}
/* No side effect */
