// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function assertEqual(expected, actual, msg) {
  if (Caml_obj.equal(expected, actual)) {
    console.log("\u001b[92mPASS: \u001b[39m" + msg);
  } else {
    console.log("\u001b[91mFAIL: \u001b[39m" + msg);
    console.log("~~~~~~~~~");
    console.log("Expected: ");
    console.log("---------");
    console.log(expected);
    console.log("");
    console.log("Received: ");
    console.log("---------");
    console.log(actual);
    console.log("~~~~~~~~~");
  }
}

exports.assertEqual = assertEqual;
/* No side effect */
