// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";

function assertEqual(expected, actual, msg) {
  if (Caml_obj.equal(expected, actual)) {
    console.log("\u001b[92mPASS: \u001b[39m" + msg);
  } else {
    console.log("\u001b[91mFAIL: \u001b[39m" + msg);
    console.log("~~~~~~~~~");
    console.log("Expected: ");
    console.log("---------");
    console.log(expected);
    console.log("");
    console.log("Received: ");
    console.log("---------");
    console.log(actual);
    console.log("~~~~~~~~~");
  }
}

export {
  assertEqual ,
}
/* No side effect */
